# Insurance cost prediction using linear regression

Make a submisson here: https://jovian.ai/learn/deep-learning-with-pytorch-zero-to-gans/assignment/assignment-2-train-your-first-model

In this assignment we're going to use information like a person's age, sex, BMI, no. of children and smoking habit to predict the price of yearly medical bills. This kind of model is useful for insurance companies to determine the yearly insurance premium for a person. The dataset for this problem is taken from [Kaggle](https://www.kaggle.com/mirichoi0218/insurance).


We will create a model with the following steps:
1. Download and explore the dataset
2. Prepare the dataset for training
3. Create a linear regression model
4. Train the model to fit the data
5. Make predictions using the trained model


This assignment builds upon the concepts from the first 2 lessons. It will help to review these Jupyter notebooks:
- PyTorch basics: https://jovian.ai/aakashns/01-pytorch-basics
- Linear Regression: https://jovian.ai/aakashns/02-linear-regression
- Logistic Regression: https://jovian.ai/aakashns/03-logistic-regression
- Linear regression (minimal): https://jovian.ai/aakashns/housing-linear-minimal
- Logistic regression (minimal): https://jovian.ai/aakashns/mnist-logistic-minimal

As you go through this notebook, you will find a **???** in certain places. Your job is to replace the **???** with appropriate code or values, to ensure that the notebook runs properly end-to-end . In some cases, you'll be required to choose some hyperparameters (learning rate, batch size etc.). Try to experiment with the hypeparameters to get the lowest loss.


In [ ]:
# Uncomment and run the appropriate command for your operating system, if required

# Linux / Binder
# !pip install numpy matplotlib pandas torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# Windows
# !pip install numpy matplotlib pandas torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# MacOS
# !pip install numpy matplotlib pandas torch torchvision torchaudio

In [126]:
import torch
import torchvision
import torch.nn as nn
import pandas as pd
import matplotlib.pyplot as plt
import torch.nn.functional as F
from torchvision.datasets.utils import download_url
from torch.utils.data import DataLoader, TensorDataset, random_split

In [127]:
project_name='02-insurance-linear-regression' # will be used by jovian.commit

## Step 1: Download and explore the data

Let us begin by downloading the data. We'll use the `download_url` function from PyTorch to get the data as a CSV (comma-separated values) file. 

In [128]:
DATASET_URL = "https://gist.github.com/BirajCoder/5f068dfe759c1ea6bdfce9535acdb72d/raw/c84d84e3c80f93be67f6c069cbdc0195ec36acbd/insurance.csv"
DATA_FILENAME = "insurance.csv"
download_url(DATASET_URL, '.')

Using downloaded and verified file: ./insurance.csv


To load the dataset into memory, we'll use the `read_csv` function from the `pandas` library. The data will be loaded as a Pandas dataframe. See this short tutorial to learn more: https://data36.com/pandas-tutorial-1-basics-reading-data-files-dataframes-data-selection/

In [129]:
dataframe_raw = pd.read_csv(DATA_FILENAME)
dataframe_raw.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

We're going to do a slight customization of the data, so that you every participant receives a slightly different version of the dataset. Fill in your name below as a string (enter at least 5 characters)

In [5]:
your_name = "Elizabeth" # at least 5 characters

The `customize_dataset` function will customize the dataset slightly using your name as a source of random numbers.

In [130]:
def customize_dataset(dataframe_raw, rand_str):
    dataframe = dataframe_raw.copy(deep=True)
    # drop some rows
    dataframe = dataframe.sample(int(0.95*len(dataframe)), random_state=int(ord(rand_str[0])))
    # scale input
    dataframe.bmi = dataframe.bmi * ord(rand_str[1])/100.
    # scale target
    dataframe.charges = dataframe.charges * ord(rand_str[2])/100.
    # drop column
    if ord(rand_str[3]) % 2 == 1:
        dataframe = dataframe.drop(['region'], axis=1)
    return dataframe

In [131]:
dataframe = customize_dataset(dataframe_raw, your_name)
dataframe.head()

age     sex      bmi  children smoker     region       charges
780    30    male  26.3520         3    yes  southwest  19172.176800
1146   60    male  35.4240         0    yes  southwest  55220.370859
1032   30  female  30.1644         0     no  northeast   4344.398835
1045   43  female  26.6760         2    yes  northwest  22974.861000
985    44  female  27.8640         1     no  southwest   8005.861500

Let us answer some basic questions about the dataset. 


**Q1: How many rows does the dataset have?**

In [132]:
num_rows = dataframe.shape[0]
print(num_rows)

1271


**Q2: How many columns doe the dataset have**

In [9]:
num_cols = dataframe.shape[1]
print(num_cols)

7


**Q3: What are the column titles of the input variables?**

In [133]:
input_cols = dataframe.drop('charges',axis=1).columns
input_cols

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region'], dtype='object')

**Q4: Which of the input columns are non-numeric or categorial variables ?**

Hint: `sex` is one of them. List the columns that are not numbers.

In [11]:
categorical_cols = list(dataframe.select_dtypes(include=['object']).columns.tolist())
print(categorical_cols)

['sex', 'smoker', 'region']


**Q5: What are the column titles of output/target variable(s)?**

In [134]:
output_cols = ['charges'] # Not quite sure what this question is asking... 

**Q: (Optional) What is the minimum, maximum and average value of the `charges` column? Can you show the distribution of values in a graph?**
Use this data visualization cheatsheet for referece: https://jovian.ai/aakashns/dataviz-cheatsheet

In [135]:
# Write your answer here

Remember to commit your notebook to Jovian after every step, so that you don't lose your work.

In [136]:
!pip install jovian --upgrade -q

In [137]:
import jovian

In [138]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.


## Step 2: Prepare the dataset for training

We need to convert the data from the Pandas dataframe into a PyTorch tensors for training. To do this, the first step is to convert it numpy arrays. If you've filled out `input_cols`, `categorial_cols` and `output_cols` correctly, this following function will perform the conversion to numpy arrays.

In [139]:
def dataframe_to_arrays(dataframe):
    # Make a copy of the original dataframe
    dataframe1 = dataframe.copy(deep=True)
    # Convert non-numeric categorical columns to numbers
    for col in categorical_cols:
        dataframe1[col] = dataframe1[col].astype('category').cat.codes
    # Extract input & outupts as numpy arrays
    inputs_array = dataframe1[input_cols].to_numpy()
    targets_array = dataframe1[output_cols].to_numpy()
    return inputs_array, targets_array

Read through the [Pandas documentation](https://pandas.pydata.org/pandas-docs/stable/user_guide/categorical.html) to understand how we're converting categorical variables into numbers.

In [140]:
inputs_array, targets_array = dataframe_to_arrays(dataframe)
inputs_array, targets_array

(array([[30.    ,  1.    , 26.352 ,  3.    ,  1.    ,  3.    ],
        [60.    ,  1.    , 35.424 ,  0.    ,  1.    ,  3.    ],
        [30.    ,  0.    , 30.1644,  0.    ,  0.    ,  0.    ],
        ...,
        [60.    ,  0.    , 27.9072,  0.    ,  0.    ,  1.    ],
        [50.    ,  1.    , 34.371 ,  0.    ,  1.    ,  0.    ],
        [42.    ,  0.    , 26.9838,  2.    ,  0.    ,  1.    ]]),
 array([[19172.1768   ],
        [55220.3708595],
        [ 4344.398835 ],
        ...,
        [30369.293766 ],
        [43152.0198375],
        [ 8417.9142075]]))

**Q6: Convert the numpy arrays `inputs_array` and `targets_array` into PyTorch tensors. Make sure that the data type is `torch.float32`.**

In [141]:
inputs = torch.from_numpy(inputs_array).to(dtype=torch.float32)
targets = torch.from_numpy(targets_array).to(dtype=torch.float32)
inputs,targets

(tensor([[30.0000,  1.0000, 26.3520,  3.0000,  1.0000,  3.0000],
         [60.0000,  1.0000, 35.4240,  0.0000,  1.0000,  3.0000],
         [30.0000,  0.0000, 30.1644,  0.0000,  0.0000,  0.0000],
         ...,
         [60.0000,  0.0000, 27.9072,  0.0000,  0.0000,  1.0000],
         [50.0000,  1.0000, 34.3710,  0.0000,  1.0000,  0.0000],
         [42.0000,  0.0000, 26.9838,  2.0000,  0.0000,  1.0000]]),
 tensor([[19172.1777],
         [55220.3711],
         [ 4344.3989],
         ...,
         [30369.2930],
         [43152.0195],
         [ 8417.9141]]))

In [142]:
inputs.dtype, targets.dtype

(torch.float32, torch.float32)

Next, we need to create PyTorch datasets & data loaders for training & validation. We'll start by creating a `TensorDataset`.

In [143]:
dataset = TensorDataset(inputs, targets)

**Q7: Pick a number between `0.1` and `0.2` to determine the fraction of data that will be used for creating the validation set. Then use `random_split` to create training & validation datasets.**

In [168]:
val_percent = 0.11  # between 0.1 and 0.2
val_size = int(num_rows * val_percent)
train_size = num_rows - val_size


train_ds, val_ds =random_split(dataset, [train_size, val_size]) # Use the random_split function to split dataset into 2 parts of the desired length

Finally, we can create data loaders for training & validation.

**Q8: Pick a batch size for the data loader.**

In [169]:
batch_size = 36

In [170]:
train_loader = DataLoader(train_ds, batch_size, shuffle=True)
val_loader = DataLoader(val_ds, batch_size)

Let's look at a batch of data to verify everything is working fine so far.

In [171]:
for xb, yb in train_loader:
    print("inputs:", xb)
    print("targets:", yb)
    break

inputs: tensor([[19.0000,  1.0000, 22.0590,  0.0000,  0.0000,  1.0000],
        [64.0000,  1.0000, 27.6480,  2.0000,  0.0000,  3.0000],
        [45.0000,  1.0000, 32.9346,  2.0000,  0.0000,  1.0000],
        [19.0000,  0.0000, 20.0880,  0.0000,  0.0000,  3.0000],
        [42.0000,  0.0000, 28.7280,  0.0000,  1.0000,  1.0000],
        [23.0000,  1.0000, 45.2628,  0.0000,  0.0000,  2.0000],
        [61.0000,  1.0000, 34.0956,  0.0000,  0.0000,  2.0000],
        [30.0000,  0.0000, 23.7006,  1.0000,  0.0000,  0.0000],
        [32.0000,  0.0000, 47.7576,  0.0000,  0.0000,  2.0000],
        [33.0000,  1.0000, 32.6700,  0.0000,  0.0000,  2.0000],
        [50.0000,  0.0000, 30.3696,  3.0000,  0.0000,  1.0000],
        [30.0000,  1.0000, 27.4968,  0.0000,  0.0000,  0.0000],
        [50.0000,  1.0000, 33.4476,  3.0000,  0.0000,  1.0000],
        [18.0000,  0.0000, 45.6192,  0.0000,  1.0000,  2.0000],
        [61.0000,  0.0000, 42.2280,  2.0000,  0.0000,  3.0000],
        [55.0000,  0.0000, 35.39

## Step 3: Create a Linear Regression Model

Our model itself is a fairly straightforward linear regression (we'll build more complex models in the next assignment). 


In [172]:
input_size = len(input_cols)
output_size = len(output_cols)

**Q9: Complete the class definition below by filling out the constructor (`__init__`), `forward`, `training_step` and `validation_step` methods.**

Hint: Think carefully about picking a good loss fuction (it's not cross entropy). Maybe try 2-3 of them and see which one works best. See https://pytorch.org/docs/stable/nn.functional.html#loss-functions

In [173]:
class InsuranceModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(input_size,output_size)                  # fill this (hint: use input_size & output_size defined above)
        
    def forward(self, xb):
        out = self.linear(xb)                          # fill this
        return out
    
    def training_step(self, batch):
        inputs, targets = batch 
        # Generate predictions
        out = self(inputs)          
        # Calcuate loss
        loss = F.l1_loss(out,targets)        # fill this
        return loss
    
    def validation_step(self, batch):
        inputs, targets = batch
        # Generate predictions
        out = self(inputs)
        # Calculate loss
        loss = F.l1_loss(out,targets)        # fill this    
        return {'val_loss': loss.detach()}
        
    def validation_epoch_end(self, outputs):
        batch_losses = [x['val_loss'] for x in outputs]
        epoch_loss = torch.stack(batch_losses).mean()  # Combine losses
        return {'val_loss': epoch_loss.item()}
    
    def epoch_end(self, epoch, result, num_epochs):
        # Print result every 20th epoch
        if (epoch+1) % 20 == 0 or epoch == num_epochs-1:
            print("Epoch [{}], val_loss: {:.4f}".format(epoch+1, result['val_loss']))

Let us create a model using the `InsuranceModel` class. You may need to come back later and re-run the next cell to reinitialize the model, in case the loss becomes `nan` or `infinity`.

In [174]:
model = InsuranceModel()

Let's check out the weights and biases of the model using `model.parameters`.

In [175]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.3973,  0.0395, -0.2997,  0.0295,  0.2374, -0.3726]],
        requires_grad=True),
 Parameter containing:
 tensor([0.0589], requires_grad=True)]

One final commit before we train the model.

In [176]:
jovian.commit(project=project_name, environment=None)

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.


In [177]:
def evaluate(model, val_loader):
    outputs = [model.validation_step(batch) for batch in val_loader]
    return model.validation_epoch_end(outputs)

def fit(epochs, lr, model, train_loader, val_loader, opt_func=torch.optim.SGD):
    history = []
    optimizer = opt_func(model.parameters(), lr)
    for epoch in range(epochs):
        # Training Phase 
        for batch in train_loader:
            loss = model.training_step(batch)
            loss.backward()
            optimizer.step()
            optimizer.zero_grad()
        # Validation phase
        result = evaluate(model, val_loader)
        model.epoch_end(epoch, result, epochs)
        history.append(result)
    return history

**Q10: Use the `evaluate` function to calculate the loss on the validation set before training.**

In [178]:
result = evaluate(model, val_loader) # Use the the evaluate function
print(result)

{'val_loss': 14513.2548828125}



We are now ready to train the model. You may need to run the training loop many times, for different number of epochs and with different learning rates, to get a good result. Also, if your loss becomes too large (or `nan`), you may have to re-initialize the model by running the cell `model = InsuranceModel()`. Experiment with this for a while, and try to get to as low a loss as possible.

**Q11: Train the model 4-5 times with different learning rates & for different number of epochs.**

Hint: Vary learning rates by orders of 10 (e.g. `1e-2`, `1e-3`, `1e-4`, `1e-5`, `1e-6`) to figure out what works.

In [179]:
epochs = 10
lr = 0.01
history1 = fit(epochs, lr, model, train_loader, val_loader)

Epoch [10], val_loss: 9181.5205


In [180]:
epochs = 20
lr = 0.001
history2 = fit(epochs, lr, model, train_loader, val_loader)

Epoch [20], val_loss: 8922.2100


In [181]:
epochs = 30
lr = 0.0001
history3 = fit(epochs, lr, model, train_loader, val_loader)

Epoch [20], val_loss: 8903.4102
Epoch [30], val_loss: 8894.3135


In [182]:
epochs = 40
lr = 0.00001
history4 = fit(epochs, lr, model, train_loader, val_loader)

Epoch [20], val_loss: 8892.5068
Epoch [40], val_loss: 8890.7227


In [183]:
epochs = 50
lr = 0.001
history5 = fit(epochs, lr, model, train_loader, val_loader)

Epoch [20], val_loss: 8755.4951
Epoch [40], val_loss: 8674.4092
Epoch [50], val_loss: 8646.9824


**Q12: What is the final validation loss of your model?**

In [189]:
val_loss = 8646.9824

Let's log the final validation loss to Jovian and commit the notebook

Now scroll back up, re-initialize the model, and try different set of values for batch size, number of epochs, learning rate etc. Commit each experiment and use the "Compare" and "View Diff" options on Jovian to compare the different results.

## Step 5: Make predictions using the trained model

**Q13: Complete the following function definition to make predictions on a single input**

In [185]:
def predict_single(input, target, model):
    inputs = input.unsqueeze(0)
    predictions = model(inputs)                # fill this
    prediction = predictions[0].detach()
    print("Input:", input)
    print("Target:", target)
    print("Prediction:", prediction)

In [186]:
input, target = val_ds[0]
predict_single(input, target, model)

Input: tensor([28.0000,  0.0000, 40.6296,  1.0000,  0.0000,  2.0000])
Target: tensor([3955.2280])
Prediction: tensor([7509.1992])


In [187]:
input, target = val_ds[10]
predict_single(input, target, model)

Input: tensor([18.0000,  1.0000, 29.5488,  1.0000,  1.0000,  0.0000])
Target: tensor([18037.6172])
Prediction: tensor([5133.7251])


In [188]:
input, target = val_ds[23]
predict_single(input, target, model)

Input: tensor([19.0000,  1.0000, 18.8784,  0.0000,  0.0000,  1.0000])
Target: tensor([1702.4072])
Prediction: tensor([4319.2998])


Are you happy with your model's predictions? Try to improve them further.

## (Optional) Step 6: Try another dataset & blog about it

While this last step is optional for the submission of your assignment, we highly recommend that you do it. Try to replicate this notebook for a different linear regression or logistic regression problem. This will help solidify your understanding, and give you a chance to differentiate the generic patterns in machine learning from problem-specific details.You can use one of these starer notebooks (just change the dataset):

- Linear regression (minimal): https://jovian.ai/aakashns/housing-linear-minimal
- Logistic regression (minimal): https://jovian.ai/aakashns/mnist-logistic-minimal

Here are some sources to find good datasets:

- https://lionbridge.ai/datasets/10-open-datasets-for-linear-regression/
- https://www.kaggle.com/rtatman/datasets-for-regression-analysis
- https://archive.ics.uci.edu/ml/datasets.php?format=&task=reg&att=&area=&numAtt=&numIns=&type=&sort=nameUp&view=table
- https://people.sc.fsu.edu/~jburkardt/datasets/regression/regression.html
- https://archive.ics.uci.edu/ml/datasets/wine+quality
- https://pytorch.org/docs/stable/torchvision/datasets.html

We also recommend that you write a blog about your approach to the problem. Here is a suggested structure for your post (feel free to experiment with it):

- Interesting title & subtitle
- Overview of what the blog covers (which dataset, linear regression or logistic regression, intro to PyTorch)
- Downloading & exploring the data
- Preparing the data for training
- Creating a model using PyTorch
- Training the model to fit the data
- Your thoughts on how to experiment with different hyperparmeters to reduce loss
- Making predictions using the model

As with the previous assignment, you can [embed Juptyer notebook cells & outputs from Jovian](https://medium.com/jovianml/share-and-embed-jupyter-notebooks-online-with-jovian-ml-df709a03064e) into your blog. 

Don't forget to share your work on the forum: https://jovian.ai/forum/t/linear-regression-and-logistic-regression-notebooks-and-blog-posts/14039